##**Boston**

In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/boston.csv'
boston = pd.read_csv(file_location)
print(boston.columns)
boston.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [3]:
boston_indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_dep = boston[['medv']]

print(boston_indep.shape, boston_dep.shape)

(506, 13) (506, 1)


##**Previous Structure**
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(10, activation='swish')(X)

Y = tf.keras.layers.Dense(1)(H)

In [4]:
X = tf.keras.layers.Input(shape=[13])

layer1 = tf.keras.layers.Dense(10)(X)
layer1 = tf.keras.layers.BatchNormalization()(layer1)
layer1 = tf.keras.layers.Activation('swish')(layer1)

layer2 = tf.keras.layers.Dense(10)(layer1)
layer2 = tf.keras.layers.BatchNormalization()(layer2)
layer2 = tf.keras.layers.Activation('swish')(layer2)

layer3 = tf.keras.layers.Dense(10)(layer2)
layer3 = tf.keras.layers.BatchNormalization()(layer3)
layer3 = tf.keras.layers.Activation('swish')(layer3)

Y = tf.keras.layers.Dense(1)(layer3)

boston_model = tf.keras.models.Model(X,Y)
boston_model.compile(loss='mse')#, metrics='accuracy')

In [5]:
boston_model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
batch_normalization (BatchNo (None, 10)                40        
_________________________________________________________________
activation (Activation)      (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
batch_normalization_1 (Batch (None, 10)                40        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0     

In [6]:
boston_model.fit(boston_indep, boston_dep, epochs=1000, verbose=0)
boston_model.fit(boston_indep, boston_dep, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 11.3951
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 10.4615
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 11.7991
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 12.6332
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 10.7029
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 11.0048
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 8.6445
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 9.2339
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 10.4219
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 10.6154


In [7]:
print(boston_model.predict(boston_indep[:5]))
print(boston_dep[:5])

[[27.194908]
 [26.352394]
 [34.308647]
 [33.22681 ]
 [33.05572 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


##**Iris**

In [8]:
import tensorflow as tf
import pandas as pd

In [10]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/iris.csv'
iris = pd.read_csv(file_location)
#To make classification, one hot encoding
encoded_data = pd.get_dummies(iris)
print(encoded_data.columns)
encoded_data.head()

Index(['Petal length', 'Petal width', 'Calyx length', 'Calyx width',
       'Species_setosa', 'Species_versicolor', 'Species_virginica'],
      dtype='object')


Petal length  Petal width  ...  Species_versicolor  Species_virginica
0           5.1          3.5  ...                   0                  0
1           4.9          3.0  ...                   0                  0
2           4.7          3.2  ...                   0                  0
3           4.6          3.1  ...                   0                  0
4           5.0          3.6  ...                   0                  0

[5 rows x 7 columns]

In [11]:
iris_indep = encoded_data[['Petal length', 'Petal width', 'Calyx length', 'Calyx width']]
iris_dep = encoded_data[['Species_setosa', 'Species_versicolor', 'Species_virginica']]

print(iris_indep.shape, iris_dep.shape)

(150, 4) (150, 3)


In [20]:
#The number of independent variable is '4'
X = tf.keras.layers.Input(shape=[4])

layer1 = tf.keras.layers.Dense(8)(X)
layer1 = tf.keras.layers.BatchNormalization()(layer1)
layer1 = tf.keras.layers.Activation('swish')(layer1)

layer2 = tf.keras.layers.Dense(8)(layer1)
layer2 = tf.keras.layers.BatchNormalization()(layer2)
layer2 = tf.keras.layers.Activation('swish')(layer2)

layer3 = tf.keras.layers.Dense(8)(layer2)
layer3 = tf.keras.layers.BatchNormalization()(layer3)
layer3 = tf.keras.layers.Activation('swish')(layer3)

Y = tf.keras.layers.Dense(3, activation='softmax')(layer3)

iris_model = tf.keras.models.Model(X,Y)
iris_model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [21]:
iris_model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 40        
_________________________________________________________________
batch_normalization_6 (Batch (None, 8)                 32        
_________________________________________________________________
activation_6 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 72        
_________________________________________________________________
batch_normalization_7 (Batch (None, 8)                 32        
_________________________________________________________________
activation_7 (Activation)    (None, 8)                 0   

In [22]:
iris_model.fit(iris_indep, iris_dep, epochs=1000, verbose=0)
iris_model.fit(iris_indep, iris_dep, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0260 - accuracy: 0.9933
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0315 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0435 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0297 - accuracy: 0.9933
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0276 - accuracy: 0.9933
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0705 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0360 - accuracy: 0.9933
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0988 - accuracy: 0.9600
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0573 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0441 - accuracy: 0.9800


In [19]:
print(iris_model.predict(iris_indep[:5]))
print(iris_dep[:5])

[[1.0000000e+00 3.8344002e-08 7.1039914e-12]
 [1.0000000e+00 2.7388539e-08 6.4468023e-12]
 [1.0000000e+00 2.4693366e-08 4.4135412e-13]
 [9.9999988e-01 9.7388650e-08 9.8008051e-12]
 [1.0000000e+00 2.3408255e-08 2.9488035e-12]]
   Species_setosa  Species_versicolor  Species_virginica
0               1                   0                  0
1               1                   0                  0
2               1                   0                  0
3               1                   0                  0
4               1                   0                  0
