#**Practice #1 - Pandas**

In [9]:
import pandas as pd

In [32]:
# Read data from files
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/lemonade.csv'
lemonade = pd.read_csv(file_location)
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/boston.csv'
boston = pd.read_csv(file_location)
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/iris.csv'
iris = pd.read_csv(file_location)

In [33]:
#Check Shape
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [34]:
#Check Columns
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['Temp', 'Sales'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['Petal length', 'Petal width', 'Calyx length', 'Calyx width',
       'Species'],
      dtype='object')


In [35]:
indep = lemonade[['Temp']]
dep = lemonade[['Sales']]
print(indep.shape, dep.shape)

indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
dep = boston[['medv']]
print(indep.shape, dep.shape)

indep = iris[['Petal length', 'Petal width', 'Calyx length', 'Calyx width']]
dep = iris[['Species']]
print(indep.shape, dep.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


##Check data

In [36]:
lemonade.head()

Temp  Sales
0    20     40
1    21     42
2    22     44
3    23     46
4    24     48

In [37]:
boston.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [38]:
iris.head()

Petal length  Petal width  Calyx length  Calyx width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#**Practice #2 - Basic Tensorflow**


```
Using Lemonade dataset
```




In [2]:
import tensorflow as tf
import pandas as pd

Read Data

In [3]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/lemonade.csv'
lemonade = pd.read_csv(file_location)

Data preparation

In [4]:
#independent variable: Temp
#dependent variable: Sales
indep = lemonade[['Temp']]
dep = lemonade[['Sales']]
print(indep.shape, dep.shape)

(6, 1) (6, 1)


Structure a model

In [5]:
#The number of independent variable is '1'
X = tf.keras.layers.Input(shape=[1])
#The number of dependent variable is '1'
Y = tf.keras.layers.Dense(1)(X)

model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

Learning the model

In [6]:
#Epochs is the number of learning
model.fit(indep,dep, epochs=10000, verbose=0)

Check the result

In [8]:
print(model.predict(indep))
dep

[[40.008144]
 [42.000538]
 [43.992935]
 [45.985332]
 [47.97773 ]
 [49.970127]]


Sales
0     40
1     42
2     44
3     46
4     48
5     50

Use the model

In [9]:
print("Predictions: ", model.predict([[15]]))

Predictions:  [[30.04616]]


#**Practice #3 - Basic Tensorflow 2**

```
Using Boston Housing Price data
Regression example
```



In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/boston.csv'
boston = pd.read_csv(file_location)
print(boston.columns)
boston.head()

Divide independnt variable and dependent variable

In [3]:
indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
dep = boston[['medv']]
print(indep.shape, dep.shape)

(506, 13) (506, 1)


Structure the model

In [4]:
#The number of independent variable is '13'
X = tf.keras.layers.Input(shape=[13])
#The number of dependent variable is '1'
Y = tf.keras.layers.Dense(1)(X)

model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

Train the model

In [11]:
#Epochs is the number of learning
model.fit(indep,dep, epochs=10000, verbose=0)
model.fit(indep,dep, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 952us/step - loss: 23.7283
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5742
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.2541
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4414
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6218
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.3280
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 24.0255
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 23.2265
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1605
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5412


Use the model to predict

In [15]:
model.predict(indep[5:10])

array([[25.17234 ],
       [21.910707],
       [18.867834],
       [10.752108],
       [18.213348]], dtype=float32)

In [16]:
dep[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

Check mathematical expression of the model

In [17]:
model.get_weights()

[array([[-0.09880063],
        [ 0.04697684],
        [-0.01244805],
        [ 2.6401615 ],
        [-5.588241  ],
        [ 5.0261583 ],
        [-0.00814669],
        [-1.1466255 ],
        [ 0.2189718 ],
        [-0.01081136],
        [-0.59958494],
        [ 0.01196189],
        [-0.47165775]], dtype=float32), array([13.57129], dtype=float32)]

#**Practice #4 - Basic Tensorflow 3**

```
Using Iris Housing Price data
Classification example
```

In [20]:
import tensorflow as tf
import pandas as pd

In [44]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/iris.csv'
iris = pd.read_csv(file_location)
#To make classification, one hot encoding
encoded_data = pd.get_dummies(iris)
print(encoded_data.columns)
encoded_data.head()

Index(['Petal length', 'Petal width', 'Calyx length', 'Calyx width',
       'Species_setosa', 'Species_versicolor', 'Species_virginica'],
      dtype='object')


Petal length  Petal width  ...  Species_versicolor  Species_virginica
0           5.1          3.5  ...                   0                  0
1           4.9          3.0  ...                   0                  0
2           4.7          3.2  ...                   0                  0
3           4.6          3.1  ...                   0                  0
4           5.0          3.6  ...                   0                  0

[5 rows x 7 columns]

In [45]:
indep = encoded_data[['Petal length', 'Petal width', 'Calyx length', 'Calyx width']]
dep = encoded_data[['Species_setosa', 'Species_versicolor', 'Species_virginica']]
print(indep.shape, dep.shape)

(150, 4) (150, 3)


In [46]:
#The number of independent variable is '4'
X = tf.keras.layers.Input(shape=[4])
#The number of dependent variable is '1' and classification
Y = tf.keras.layers.Dense(3, activation='softmax')(X)

model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [47]:
model.fit(indep, dep, epochs=1000, verbose=0)
model.fit(indep, dep, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1604 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1610 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1600 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1601 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1601 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1597 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1602 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1595 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1594 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1591 - accuracy: 0.9667


In [50]:
model.predict(indep[-5:])

array([[2.9582105e-07, 9.0524666e-02, 9.0947509e-01],
       [1.0230059e-06, 1.7404507e-01, 8.2595396e-01],
       [1.9761146e-06, 2.0985842e-01, 7.9013962e-01],
       [3.5036928e-07, 8.2116485e-02, 9.1788322e-01],
       [5.7489397e-06, 2.7777135e-01, 7.2222286e-01]], dtype=float32)

In [51]:
dep[-5:]

Species_setosa  Species_versicolor  Species_virginica
145               0                   0                  1
146               0                   0                  1
147               0                   0                  1
148               0                   0                  1
149               0                   0                  1

In [52]:
model.get_weights()

[array([[ 1.3130723 ,  0.8596317 ,  0.01862541],
        [ 2.8007426 ,  0.09926595, -1.2272661 ],
        [-3.1697485 , -0.2339781 ,  0.85000265],
        [-4.8240895 , -0.99405706,  2.838175  ]], dtype=float32),
 array([ 1.5998452,  1.2986244, -1.2306257], dtype=float32)]

#**Practice #5 - Hidden Layer**

```
Multi Layer
Using boston data
```

In [53]:
import tensorflow as tf
import pandas as pd

In [54]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/boston.csv'
boston = pd.read_csv(file_location)
print(boston.columns)
boston.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [63]:
boston_indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_dep = boston[['medv']]

print(boston_indep.shape, boston_dep.shape)

(506, 13) (506, 1)


In [77]:
X = tf.keras.layers.Input(shape=[13])
#Hidden Layer
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)

boston_model = tf.keras.models.Model(X,Y)
boston_model.compile(loss='mse')#, metrics='accuracy')

In [78]:
#To see the created model
boston_model.summary()

Model: "model_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_15 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [82]:
boston_model.fit(boston_indep, boston_dep, epochs=1000, verbose=0)
boston_model.fit(boston_indep, boston_dep, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4102
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 22.3463
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 22.7632
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9755
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 21.5044
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.0604
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 22.5431
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8624
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 22.1505
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8603


In [83]:
print(boston_model.predict(boston_indep[:5]))
print(boston_dep[:5])

[[29.864569]
 [24.639565]
 [30.956131]
 [29.762825]
 [29.32112 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


#**Practice #6 - Hidden Layer2**

```
Multi Layer
Using Iris data
```

In [85]:
import tensorflow as tf
import pandas as pd

In [86]:
file_location = 'https://raw.githubusercontent.com/Myeongjung/ML_Practice/master/csv/iris.csv'
iris = pd.read_csv(file_location)
#To make classification, one hot encoding
encoded_data = pd.get_dummies(iris)
print(encoded_data.columns)
encoded_data.head()

Index(['Petal length', 'Petal width', 'Calyx length', 'Calyx width',
       'Species_setosa', 'Species_versicolor', 'Species_virginica'],
      dtype='object')


Petal length  Petal width  ...  Species_versicolor  Species_virginica
0           5.1          3.5  ...                   0                  0
1           4.9          3.0  ...                   0                  0
2           4.7          3.2  ...                   0                  0
3           4.6          3.1  ...                   0                  0
4           5.0          3.6  ...                   0                  0

[5 rows x 7 columns]

In [87]:
iris_indep = encoded_data[['Petal length', 'Petal width', 'Calyx length', 'Calyx width']]
iris_dep = encoded_data[['Species_setosa', 'Species_versicolor', 'Species_virginica']]

print(iris_indep.shape, iris_dep.shape)

(150, 4) (150, 3)


In [93]:
#The number of independent variable is '4'
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(5, activation='swish')(H)
#The number of dependent variable is '1' and classification
Y = tf.keras.layers.Dense(3, activation='softmax')(H)

iris_model = tf.keras.models.Model(X,Y)
iris_model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [94]:
#To see the created model
iris_model.summary()

Model: "model_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 4)]               0         
_________________________________________________________________
dense_20 (Dense)             (None, 5)                 25        
_________________________________________________________________
dense_21 (Dense)             (None, 5)                 30        
_________________________________________________________________
dense_22 (Dense)             (None, 5)                 30        
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 18        
Total params: 103
Trainable params: 103
Non-trainable params: 0
_________________________________________________________________


In [ ]:
iris_model.fit(iris_indep, iris_dep, epochs=1000, verbose=0)
iris_model.fit(iris_indep, iris_dep, epochs=10)

In [96]:
print(iris_model.predict(iris_indep[:5]))
print(iris_dep[:5])

[[1.0000000e+00 3.4217181e-11 1.5637101e-12]
 [1.0000000e+00 3.0340397e-09 8.2186299e-11]
 [1.0000000e+00 6.5659278e-10 2.3465528e-11]
 [1.0000000e+00 9.0501979e-09 1.7843438e-10]
 [1.0000000e+00 3.0296647e-11 1.3195968e-12]]
   Species_setosa  Species_versicolor  Species_virginica
0               1                   0                  0
1               1                   0                  0
2               1                   0                  0
3               1                   0                  0
4               1                   0                  0
